# Pin to a specific tag once you know the E+ version you want
FROM nrel/energyplus:latest

USER root

# Install python + pip + your deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir numpy
RUN pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch

WORKDIR /app

# Your script
COPY run_sim_train.py /app/run_sim_train.py
COPY eplus_runperiod_utils.py /app/eplus_runperiod_utils.py
COPY andruix_policy_model.py /app/andruix_policy_model.py
COPY andruix_rollout_writer.py /app/andruix_rollout_writer.py
COPY andruix_simple_model.py /app/andruix_simple_model.py
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh && sed -i 's/\r$//' /app/entrypoint.sh

# Put required sim assets *inside* the container
RUN mkdir -p /home/guser/weather /home/guser/models /home/guser/results

# Copy the IDF/EPW from build context into the image
COPY eplus_req/weather/ /home/guser/weather/
COPY eplus_req/models/  /home/guser/models/

# (Optional) make sure results dir is writable
RUN chmod -R a+rX /home/guser && chmod -R a+rwX /home/guser/results

ENTRYPOINT ["/app/entrypoint.sh"]
